package com.hfrontier.teamb.repository;

import java.util.Date;

public class Comments {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.id
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.user_id
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.count_log
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private Integer countLog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.comment
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.delete_flag
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private String deleteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.created_at
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.updated_at
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.id
	 * @return  the value of comments.id
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.id
	 * @param id  the value for comments.id
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.user_id
	 * @return  the value of comments.user_id
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.user_id
	 * @param userId  the value for comments.user_id
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.count_log
	 * @return  the value of comments.count_log
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public Integer getCountLog() {
		return countLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.count_log
	 * @param countLog  the value for comments.count_log
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setCountLog(Integer countLog) {
		this.countLog = countLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.comment
	 * @return  the value of comments.comment
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.comment
	 * @param comment  the value for comments.comment
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.delete_flag
	 * @return  the value of comments.delete_flag
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.delete_flag
	 * @param deleteFlag  the value for comments.delete_flag
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.created_at
	 * @return  the value of comments.created_at
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.created_at
	 * @param createdAt  the value for comments.created_at
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.updated_at
	 * @return  the value of comments.updated_at
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.updated_at
	 * @param updatedAt  the value for comments.updated_at
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}