package com.hfrontier.teamb.repository;

import java.util.Date;

public class Members {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.id
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.password
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.count
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.create_time
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.id
	 * @return  the value of members.id
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.id
	 * @param id  the value for members.id
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.password
	 * @return  the value of members.password
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.password
	 * @param password  the value for members.password
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.count
	 * @return  the value of members.count
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.count
	 * @param count  the value for members.count
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.create_time
	 * @return  the value of members.create_time
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.create_time
	 * @param createTime  the value for members.create_time
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}