package com.hfrontier.teamb.repository;

public class Members {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.id
	 * @mbg.generated  Thu Apr 04 21:12:17 JST 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.password
	 * @mbg.generated  Thu Apr 04 21:12:17 JST 2019
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.id
	 * @return  the value of members.id
	 * @mbg.generated  Thu Apr 04 21:12:17 JST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.id
	 * @param id  the value for members.id
	 * @mbg.generated  Thu Apr 04 21:12:17 JST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.password
	 * @return  the value of members.password
	 * @mbg.generated  Thu Apr 04 21:12:17 JST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.password
	 * @param password  the value for members.password
	 * @mbg.generated  Thu Apr 04 21:12:17 JST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}


}