package com.hfrontier.teamb.mapper;

import com.hfrontier.teamb.repository.Comments;

public interface CommentsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int insert(Comments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int insertSelective(Comments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	Comments selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int updateByPrimaryKeySelective(Comments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int updateByPrimaryKey(Comments record);
}