package com.hfrontier.teamb.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.hfrontier.teamb.repository.Comments;
@Mapper
public interface CommentsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int insert(Comments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int insertSelective(Comments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	Comments selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int updateByPrimaryKeySelective(Comments record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 28 20:42:23 JST 2019
	 */
	int updateByPrimaryKey(Comments record);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 10 10:54:49 JST 2018
     */
	int getCountLog(@Param("userID") String userID);
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *コメント登録用
     * @mbg.generated Mon Oct 10 10:54:49 JST 2018
     */
	int insertComment(String userID,int countLog,String comment);

}