package com.hfrontier.teamb.mapper;

import com.hfrontier.teamb.repository.Members;

public interface MembersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	int insert(Members record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbg.generated  Wed Mar 20 21:52:18 JST 2019
	 */
	int insertSelective(Members record);

	Members selectByPrimaryKey(String userId);
}